# Generated by Django 3.2.9 on 2021-11-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
