# Generated by Django 3.2.9 on 2021-11-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_userinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
