# Generated by Django 3.0.4 on 2020-04-03 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('filename', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'], message='必须为xls或xlsx文件')])),
                ('file_type', models.IntegerField(choices=[(1, '学生信息'), (2, '成绩信息')], default=1, help_text='file_type/文件类型', verbose_name='文件类型')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'file',
            },
        ),
    ]
