# Generated by Django 3.0.4 on 2020-04-09 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='filename',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.FileField(default=2, help_text='file_type/上传文件名', upload_to='', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'], message='必须为xls或xlsx文件')], verbose_name='上传文件名'),
            preserve_default=False,
        ),
    ]
